-- Keystone Field Service Management Initial Schema
-- Supports both H2 and PostgreSQL (using SQL:2003 standard types)

-- 1. Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL
);
CREATE INDEX idx_users_username ON users(username);

-- 2. Technicians Table
CREATE TABLE technicians (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    name VARCHAR(255) NOT NULL,
    skills VARCHAR(500) NOT NULL,
    status VARCHAR(50) NOT NULL,
    contact_number VARCHAR(100),
    rating DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_technicians_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 3. Customer Profiles Table
CREATE TABLE customer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    company_name VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_customers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 4. Buildings Table
CREATE TABLE buildings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_profile_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    CONSTRAINT fk_buildings_customer FOREIGN KEY (customer_profile_id) REFERENCES customer_profiles(id) ON DELETE CASCADE
);

-- 5. Sites Table
CREATE TABLE sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT fk_sites_building FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE CASCADE
);

-- 6. Contacts Table
CREATE TABLE contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_profile_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(100),
    role VARCHAR(255),
    CONSTRAINT fk_contacts_customer FOREIGN KEY (customer_profile_id) REFERENCES customer_profiles(id) ON DELETE CASCADE
);

-- 7. Customer Requests Table
CREATE TABLE customer_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    category VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_requests_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 8. Work Orders Table
CREATE TABLE work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    technician_id BIGINT,
    customer_request_id BIGINT UNIQUE,
    location VARCHAR(255) NOT NULL,
    scheduled_date TIMESTAMP,
    completed_date TIMESTAMP,
    parts_used VARCHAR(500),
    time_spent_minutes INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_work_orders_technician FOREIGN KEY (technician_id) REFERENCES technicians(id) ON DELETE SET NULL,
    CONSTRAINT fk_work_orders_request FOREIGN KEY (customer_request_id) REFERENCES customer_requests(id) ON DELETE SET NULL
);
CREATE INDEX idx_work_orders_technician ON work_orders(technician_id);
CREATE INDEX idx_work_orders_status ON work_orders(status);

-- 9. Notifications Table
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message VARCHAR(500) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 10. Refresh Tokens Table
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 11. Password Reset Tokens Table
CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 12. Assets Table
CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    serial_number VARCHAR(255) NOT NULL UNIQUE,
    model VARCHAR(255),
    purchase_date TIMESTAMP,
    warranty_expiration TIMESTAMP,
    customer_profile_id BIGINT NOT NULL,
    building_id BIGINT,
    maintenance_history VARCHAR(2000) DEFAULT '',
    qr_code_data VARCHAR(255),
    CONSTRAINT fk_assets_customer FOREIGN KEY (customer_profile_id) REFERENCES customer_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_assets_building FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE SET NULL
);
CREATE INDEX idx_assets_serial ON assets(serial_number);

-- 13. Spare Parts Table
CREATE TABLE spare_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(500),
    unit_price DOUBLE PRECISION NOT NULL,
    stock_level INTEGER NOT NULL DEFAULT 0,
    reorder_point INTEGER NOT NULL DEFAULT 5
);

-- 14. Warehouses Table
CREATE TABLE warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255)
);

-- 15. Inventory Stocks Table
CREATE TABLE inventory_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spare_part_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_stocks_part FOREIGN KEY (spare_part_id) REFERENCES spare_parts(id) ON DELETE CASCADE,
    CONSTRAINT fk_stocks_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE,
    CONSTRAINT uq_stock_part_warehouse UNIQUE (spare_part_id, warehouse_id)
);
CREATE INDEX idx_stocks_mapping ON inventory_stocks(spare_part_id, warehouse_id);

-- 16. Purchase Orders Table
CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255) NOT NULL UNIQUE,
    vendor_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- 17. Purchase Order Items Table
CREATE TABLE purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    spare_part_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_po_items_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_po_items_part FOREIGN KEY (spare_part_id) REFERENCES spare_parts(id) ON DELETE CASCADE
);

-- 18. SLA Policies Table
CREATE TABLE sla_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    priority VARCHAR(50) NOT NULL UNIQUE,
    response_time_hours INTEGER NOT NULL DEFAULT 2,
    resolution_time_hours INTEGER NOT NULL DEFAULT 24
);

-- 19. Attendances Table
CREATE TABLE attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technician_id BIGINT NOT NULL,
    date DATE NOT NULL,
    check_in TIMESTAMP NOT NULL,
    check_out TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'PRESENT',
    CONSTRAINT fk_attendance_tech FOREIGN KEY (technician_id) REFERENCES technicians(id) ON DELETE CASCADE
);

-- 20. Audit Logs Table
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(50) NOT NULL,
    entity_name VARCHAR(255),
    entity_id BIGINT,
    performed_by VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    details VARCHAR(1000)
);
CREATE INDEX idx_audit_logs_timestamp ON audit_logs(timestamp);

-- 21. Request Attachments Table
CREATE TABLE request_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_request_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_type VARCHAR(255),
    uploaded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_attachments_request FOREIGN KEY (customer_request_id) REFERENCES customer_requests(id) ON DELETE CASCADE
);
